input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # Partition by service field sent from logback
  if ![service] {
    mutate {
      add_field => { "service" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{service}-%{+YYYY.MM.dd}"
  }
  
  # Useful for debugging during setup
  stdout { codec => rubydebug }
}