spring.application.name=notification-service
server.port=8006
spring.cloud.config.enabled=true
# spring.config.import=optional:configserver:http://localhost:9999,optional:file:../.env[.properties],optional:file:../../.env[.properties]
# spring.config.import=configserver:http://localhost:9999,file:../.env[.properties],file:../../.env[.properties]
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:9999},optional:file:../.env[.properties],optional:file:../../.env[.properties]


spring.datasource.url=jdbc:postgresql://localhost:5432/smartsure_auth
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


# for otp verfication
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}

# for email notification
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logstash.host=${LOGSTASH_HOST:localhost}
