version: '3.8'

services:
  # 1. INFRASTRUCTURE
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-170804}
      POSTGRES_DB: smart_sure
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - private-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - private-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - private-network

  # 2. SPRING CLOUD
  eureka-server:
    build: ./backend/eureka-server
    image: ${DOCKER_USERNAME}/smartsure-eureka-server:latest
    container_name: eureka-server
    env_file: .env
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=false
      - EUREKA_CLIENT_FETCH-REGISTRY=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - private-network
      - proxy-network

  config-server:
    build: ./backend/config-server
    image: ${DOCKER_USERNAME}/smartsure-config-server:latest
    container_name: config-server
    env_file: .env
    ports:
      - "9999:9999"
    extra_hosts:
      - "github.com:20.207.73.82"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/mohansaivenkat/SmartSure-Config-Server.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - private-network

  # 3. MICROSERVICES
  auth-service:
    build: ./backend/auth-service
    image: ${DOCKER_USERNAME}/smartsure-auth-service:latest
    container_name: auth-service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:9999
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9999
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - private-network

  admin-service:
    build: ./backend/admin-service
    image: ${DOCKER_USERNAME}/smartsure-admin-service:latest
    container_name: admin-service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:9999
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9999
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - private-network

  policy-service:
    build: ./backend/policy-service
    image: ${DOCKER_USERNAME}/smartsure-policy-service:latest
    container_name: policy-service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:9999
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9999
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      config-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - private-network

  claims-service:
    build: ./backend/claims-service
    image: ${DOCKER_USERNAME}/smartsure-claims-service:latest
    container_name: claims-service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:9999
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9999
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - private-network

  payment-service:
    build: ./backend/payment-service
    image: ${DOCKER_USERNAME}/smartsure-payment-service:latest
    container_name: payment-service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:9999
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9999
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - private-network

  notification-service:
    build: ./backend/notification-service
    image: ${DOCKER_USERNAME}/smartsure-notification-service:latest
    container_name: notification-service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:9999
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9999
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - private-network

  # 4. API GATEWAY
  api-gateway:
    build: ./backend/api-gateway
    image: ${DOCKER_USERNAME}/smartsure-api-gateway:latest
    container_name: api-gateway
    env_file: .env
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:9999
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9999
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - private-network
      - proxy-network

  # 5. FRONTEND
  frontend:
    build: ./frontend
    image: ${DOCKER_USERNAME}/smartsure-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - private-network
      - proxy-network

  # 6. LOGGING (ELK STACK)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # Internal only
    networks:
      - private-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    # Internal only
    depends_on:
      - elasticsearch
    networks:
      - private-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - CSP_STRICT=false
      - SERVER_PUBLICBASEURL=http://kibana.smartsureinsurance.work.gd
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - private-network
      - proxy-network

  # 7. OBSERVABILITY (Metrics & Tracing)
  zipkin-mysql:
    image: mysql:8.0
    container_name: zipkin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: zipkin_root_pass
      MYSQL_DATABASE: zipkin
      MYSQL_USER: zipkin_user
      MYSQL_PASSWORD: zipkin_pass
    volumes:
      - zipkin-mysql-data:/var/lib/mysql
    networks:
      - private-network
    command: --default-authentication-plugin=mysql_native_password

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      STORAGE_TYPE: mysql
      MYSQL_HOST: zipkin-mysql
      MYSQL_TCP_PORT: 3306
      MYSQL_USER: zipkin_user
      MYSQL_PASS: zipkin_pass
      MYSQL_DB: zipkin
    depends_on:
      - zipkin-mysql
    ports:
      - "9411:9411"
    networks:
      - private-network
      - proxy-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./backend/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - private-network
      - proxy-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - private-network
      - proxy-network

networks:
  private-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
    name: smartsure-private
  proxy-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
    name: smartsure-proxy

volumes:
  postgres-data:
  zipkin-mysql-data:
  prometheus-data:
  grafana-data:
