spring.application.name=claims-service
server.port=8003
spring.cloud.config.enabled=true
# spring.config.import=optional:configserver:http://localhost:9999,optional:file:../.env[.properties],optional:file:../../.env[.properties]
# spring.config.import=configserver:http://localhost:9999,file:../.env[.properties],file:../../.env[.properties]
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:9999},optional:file:../.env[.properties],optional:file:../../.env[.properties]

#------ rabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:guest}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:guest}
