spring.application.name=payment-service
server.port=8085

# Fetch config from Config Server
spring.cloud.config.enabled=true
# spring.config.import=optional:configserver:http://localhost:9999
# spring.config.import=configserver:http://localhost:9999,file:../.env[.properties],file:../../.env[.properties]
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:9999},optional:file:../.env[.properties],optional:file:../../.env[.properties]
