package com.group2.policy_service.config;

import com.group2.policy_service.entity.PolicyCategory;
import com.group2.policy_service.entity.PolicyType;
import com.group2.policy_service.repository.PolicyTypeRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDateTime;

@Configuration
public class DataSeeder {

    @Bean
    CommandLineRunner seedData(PolicyTypeRepository typeRepository, 
                              com.group2.policy_service.repository.PolicyRepository policyRepository,
                              org.springframework.jdbc.core.JdbcTemplate jdbcTemplate) {
        return args -> {
            // 1. AUTOMATICALLY FIX THE "ID" ISSUE
            try {
                jdbcTemplate.execute("ALTER TABLE policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;");
                System.out.println("\u2705 Automatically fixed Policy Table ID generation!");
            } catch (Exception e) {
                // Already an identity column, can safely ignore
            }

            // 1.5 AUTO-FIX: BACKFILL COVERAGE FOR EXISTING USER POLICIES
            try {
                // If any user policies exist with NULL coverage, copy it from their master policy
                jdbcTemplate.execute("UPDATE user_policies SET coverage_amount = p.coverage_amount FROM policies p WHERE user_policies.policy_id = p.id AND user_policies.coverage_amount IS NULL;");
                System.out.println("\u2705 Automatically fixed coverage amounts for existing users!");
            } catch (Exception e) {
                // Table might not exist yet during the very first run
            }

            // 2. CREATE CATEGORIES (POLICY TYPES)
            if (typeRepository.count() == 0) {
                PolicyType healthType = new PolicyType();
                healthType.setCategory(PolicyCategory.HEALTH);
                healthType.setDescription("Medical and hospitalization coverage");
                healthType = typeRepository.save(healthType);

                PolicyType vehicleType = new PolicyType();
                vehicleType.setCategory(PolicyCategory.VEHICLE);
                vehicleType.setDescription("Auto, motorcycle, and road assistance");
                vehicleType = typeRepository.save(vehicleType);

                PolicyType lifeType = new PolicyType();
                lifeType.setCategory(PolicyCategory.LIFE);
                lifeType.setDescription("Term life and permanent life insurance");
                lifeType = typeRepository.save(lifeType);

                System.out.println("\u2705 Seeded default Policy Categories: HEALTH, VEHICLE, LIFE");

                // 3. CREATE SAMPLE POLICIES
                if (policyRepository.count() == 0) {
                    createPolicy(policyRepository, "Family Shield Health", "Comprehensive health cover for the whole family.", healthType, 1200.0, 500000.0, 12);
                    createPolicy(policyRepository, "Accident Guard Pro", "Professional cover for vehicle accidents and damages.", vehicleType, 800.0, 200000.0, 12);
                    createPolicy(policyRepository, "Simple Term Life", "Basic life insurance coverage at low cost.", lifeType, 1000.0, 1000000.0, 120);
                    System.out.println("\u2705 Seeded Sample Policies!");
                }
            }
        };
    }

    private void createPolicy(com.group2.policy_service.repository.PolicyRepository repo, String name, String desc, PolicyType type, Double premium, Double coverage, int duration) {
        com.group2.policy_service.entity.Policy p = new com.group2.policy_service.entity.Policy();
        p.setPolicyName(name);
        p.setDescription(desc);
        p.setPolicyType(type);
        p.setPremiumAmount(premium);
        p.setCoverageAmount(coverage);
        p.setDurationInMonths(duration);
        p.setActive(true);
        repo.save(p);
    }
}
